version: '3.9'

services:
  dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb
    env_file:
      - .env
    ports:
      - "${DYNAMODB_PORT}:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  awscli:
    image: amazon/aws-cli:latest
    stdin_open: true
    tty: true
    entrypoint: tail -f /dev/null
    env_file:
      - .env
  server:
    build: 
      context: backend
      dockerfile: ./Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./backend/src:/code/src
    ports:
      - ${API_SERVER_PORT}:8000